// FILE AUTO-GENERATED BY tools/xxd.py, DO NOT EDIT

#include "embedded_files_map.h"

std::unordered_map<std::string, std::pair<const unsigned char*, size_t>> eFiles = {
    {"160423230.png", { fn160423230_png, fn160423230_png_len } },
    {"favicon.ico", { favicon_ico, favicon_ico_len } },
    {"fetching.png", { fetching_png, fetching_png_len } },
    {"icon.svg", { icon_svg, icon_svg_len } },
    {"index.html", { index_html, index_html_len } },
    {"instagram.png", { instagram_png, instagram_png_len } },
    {"loading.html", { loading_html, loading_html_len } },
    {"react.svg", { react_svg, react_svg_len } },
    {"sc12script.js", { sc12script_js, sc12script_js_len } },
    {"assets/index-C1P3sTHY.js", { assets_index_C1P3sTHY_js, assets_index_C1P3sTHY_js_len } },
    {"assets/index-R9zuAFhJ.css", { assets_index_R9zuAFhJ_css, assets_index_R9zuAFhJ_css_len } },
    {"assets/logo-BYWJW3-1.png", { assets_logo_BYWJW3_1_png, assets_logo_BYWJW3_1_png_len } },
};
