// FILE AUTO-GENERATED BY tools/xxd.py, DO NOT EDIT

#ifndef ASSETS_INDEX_C1P3STHY_JS_H
#define ASSETS_INDEX_C1P3STHY_JS_H

extern const unsigned char assets_index_C1P3sTHY_js[];
extern const unsigned int assets_index_C1P3sTHY_js_len;

#endif // ASSETS_INDEX_C1P3STHY_JS_H
