// FILE AUTO-GENERATED BY tools/xxd.py, DO NOT EDIT

#ifndef ASSETS_INDEX_R9ZUAFHJ_CSS_H
#define ASSETS_INDEX_R9ZUAFHJ_CSS_H

extern const unsigned char assets_index_R9zuAFhJ_css[];
extern const unsigned int assets_index_R9zuAFhJ_css_len;

#endif // ASSETS_INDEX_R9ZUAFHJ_CSS_H
