// FILE AUTO-GENERATED BY tools/xxd.py, DO NOT EDIT

#ifndef ASSETS_LOGO_BYWJW3_1_PNG_H
#define ASSETS_LOGO_BYWJW3_1_PNG_H

extern const unsigned char assets_logo_BYWJW3_1_png[];
extern const unsigned int assets_logo_BYWJW3_1_png_len;

#endif // ASSETS_LOGO_BYWJW3_1_PNG_H
