// FILE AUTO-GENERATED BY tools/xxd.py, DO NOT EDIT

#ifndef FAVICON_ICO_H
#define FAVICON_ICO_H

extern const unsigned char favicon_ico[];
extern const unsigned int favicon_ico_len;

#endif // FAVICON_ICO_H
