// FILE AUTO-GENERATED BY tools/xxd.py, DO NOT EDIT

#ifndef FETCHING_PNG_H
#define FETCHING_PNG_H

extern const unsigned char fetching_png[];
extern const unsigned int fetching_png_len;

#endif // FETCHING_PNG_H
