// FILE AUTO-GENERATED BY tools/xxd.py, DO NOT EDIT

#ifndef FN160423230_PNG_H
#define FN160423230_PNG_H

extern const unsigned char fn160423230_png[];
extern const unsigned int fn160423230_png_len;

#endif // FN160423230_PNG_H
