// FILE AUTO-GENERATED BY tools/xxd.py, DO NOT EDIT

#ifndef INDEX_HTML_H
#define INDEX_HTML_H

extern const unsigned char index_html[];
extern const unsigned int index_html_len;

#endif // INDEX_HTML_H
