// FILE AUTO-GENERATED BY tools/xxd.py, DO NOT EDIT

#ifndef INSTAGRAM_PNG_H
#define INSTAGRAM_PNG_H

extern const unsigned char instagram_png[];
extern const unsigned int instagram_png_len;

#endif // INSTAGRAM_PNG_H
