// FILE AUTO-GENERATED BY tools/xxd.py, DO NOT EDIT

#ifndef LOADING_HTML_H
#define LOADING_HTML_H

extern const unsigned char loading_html[];
extern const unsigned int loading_html_len;

#endif // LOADING_HTML_H
