// FILE AUTO-GENERATED BY tools/xxd.py, DO NOT EDIT

#ifndef SC12SCRIPT_JS_H
#define SC12SCRIPT_JS_H

extern const unsigned char sc12script_js[];
extern const unsigned int sc12script_js_len;

#endif // SC12SCRIPT_JS_H
