#Author: github.com/stzyium
#Email: styyzy@github.com
#License: MIT
#Date: 2025-08-16
#File: xxd.py

import os
import stat
import sys


def file_to_c_array_header(array_name):
    """Generate extern declaration for header file."""
    return f"extern const unsigned char {array_name}[];\nextern const unsigned int {array_name}_len;\n"

def file_to_c_array_impl(input_file, array_name):
    """Convert a file to a C unsigned char array implementation."""
    with open(input_file, "rb") as f:
        data = f.read()
    lines = []
    line = ""
    for i, b in enumerate(data):
        line += f"0x{b:02x}, "
        if (i + 1) % 12 == 0:
            lines.append(line)
            line = ""
    if line:
        lines.append(line)
    array = f"const unsigned char {array_name}[] = {{\n"
    array += "\n".join(f"    {l}" for l in lines)
    array += f"\n}};\nconst unsigned int {array_name}_len = {len(data)};\n\n"
    return array


def sanitize_array_name(path):
    """Sanitize path to be a valid C array name."""
    name = path.replace("/", "_").replace("\\", "_").replace(".", "_").replace("-", "_")
    if name[0].isdigit():
        name = f"fn{name}"
    return name


def process_folder(input_folder, output_folder):
    embedded_files = []
    os.makedirs(output_folder, exist_ok=True)
    all_implementations = []
    
    for root, dirs, files in os.walk(input_folder):
        for filename in files:
            full_path = os.path.join(root, filename)
            rel_path = os.path.relpath(full_path, input_folder).replace("\\", "/")
            array_name = sanitize_array_name(rel_path)
            header_code = f"#ifndef {array_name.upper()}_H\n"
            header_code += f"#define {array_name.upper()}_H\n\n"
            header_code += file_to_c_array_header(array_name)
            header_code += f"\n#endif // {array_name.upper()}_H\n"

            header_file = os.path.join(output_folder, f"{array_name}.h")
            with open(header_file, "w") as f:
                f.write("// FILE AUTO-GENERATED BY tools/xxd.py, DO NOT EDIT\n\n")
                f.write(header_code)
            impl_code = file_to_c_array_impl(full_path, array_name)
            all_implementations.append(impl_code)
            embedded_files.append((rel_path, array_name))
    with open("c++/embedded_files_data.cc", "w") as f:
        f.write("// FILE AUTO-GENERATED BY tools/xxd.py, DO NOT EDIT\n\n")
        for _, array_name in embedded_files:
            f.write(f'#include "{input_folder}_embedded/{array_name}.h"\n')
        f.write("\n")
        for impl in all_implementations:
            f.write(impl)

    return embedded_files
if len(sys.argv) > 1:
    input_folder = sys.argv[1]
else:
    input_folder = "static"
if len(sys.argv) > 2:
    output_folder = sys.argv[2]
else:
    output_folder = "c++/{}_embedded".format(input_folder)
os.remove(f"c++/include/embedded_files_map.h") if os.path.exists(f"c++/include/embedded_files_map.h") else None
os.remove("c++/embedded_files_map.cc") if os.path.exists("c++/embedded_files_map.cc") else None
os.remove("c++/embedded_files_data.cc") if os.path.exists("c++/embedded_files_data.cc") else None

if output_folder in os.listdir():
    dir_path = os.path.join(os.getcwd(), output_folder)
    for root, dirs, files in os.walk(dir_path, topdown=False):
        for name in files:
            file_path = os.path.join(root, name)
            os.chmod(file_path, stat.S_IWRITE)
            os.remove(file_path)
        for name in dirs:
            dir_to_remove = os.path.join(root, name)
            os.chmod(dir_to_remove, stat.S_IWRITE)
            os.rmdir(dir_to_remove)

    os.chmod(dir_path, stat.S_IWRITE)
    os.rmdir(dir_path)

embedded_files = process_folder(input_folder, output_folder)
with open("c++/include/embedded_files_map.h", "w") as f:
    f.write("// FILE AUTO-GENERATED BY tools/xxd.py, DO NOT EDIT\n\n")
    f.write("#ifndef EMBEDDED_FILES_MAP_H\n")
    f.write("#define EMBEDDED_FILES_MAP_H\n\n")
    f.write("#include <unordered_map>\n#include <string>\n\n")
    for _, array_name in embedded_files:
        f.write(f'#include "../{input_folder}_embedded/{array_name}.h"\n')
    f.write("\n")
    f.write("extern std::unordered_map<std::string, std::pair<const unsigned char*, size_t>> eFiles;\n\n")
    f.write("#endif // EMBEDDED_FILES_MAP_H\n")
with open("c++/embedded_files_map.cc", "w") as f:
    f.write("// FILE AUTO-GENERATED BY tools/xxd.py, DO NOT EDIT\n\n")
    f.write('#include "embedded_files_map.h"\n\n')
    f.write("std::unordered_map<std::string, std::pair<const unsigned char*, size_t>> eFiles = {\n")
    for rel_path, array_name in embedded_files:
        f.write(f'    {{"{rel_path}", {{ {array_name}, {array_name}_len }} }},\n')
    f.write("};\n")

print(f"Embedded {len(embedded_files)} files from '{input_folder}' into '{output_folder}'")
print("Created files:")
print(f"  - {len(embedded_files)} header files in {output_folder}/")
print(f"  - {output_folder}/embedded_files_data.cc (implementations)")
print("  - embedded_files_map.h (declarations)")
print("  - embedded_files_map.cc (map implementation)")
print("\nDon't forget to add embedded_files_map.cc and {}/embedded_files_data.cc to your build!".format(output_folder))