// FILE AUTO-GENERATED BY tools/xxd.py, DO NOT EDIT

#ifndef EMBEDDED_FILES_MAP_H
#define EMBEDDED_FILES_MAP_H

#include <unordered_map>
#include <string>

#include "../static_embedded/fn160423230_png.h"
#include "../static_embedded/favicon_ico.h"
#include "../static_embedded/fetching_png.h"
#include "../static_embedded/icon_svg.h"
#include "../static_embedded/index_html.h"
#include "../static_embedded/instagram_png.h"
#include "../static_embedded/loading_html.h"
#include "../static_embedded/react_svg.h"
#include "../static_embedded/sc12script_js.h"
#include "../static_embedded/assets_index_C1P3sTHY_js.h"
#include "../static_embedded/assets_index_R9zuAFhJ_css.h"
#include "../static_embedded/assets_logo_BYWJW3_1_png.h"

extern std::unordered_map<std::string, std::pair<const unsigned char*, size_t>> eFiles;

#endif // EMBEDDED_FILES_MAP_H
